apiVersion: v1
kind: Service
metadata:
  name: uchii-ui-react-service
  labels:
    app: react-app
spec:
  type: NodePort
  selector:
    app: react-app
  ports:
    - port: 5173          # The port that the service will expose
      targetPort: 5173    # The port on the container to which the traffic will be forwarded
      nodePort: 30002     # The port on each node that will forward to the service